{% set version = "0.10.1" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: exa
  version: {{ version }}

source:
  url: https://github.com/ogham/exa/archive/v{{ version }}.tar.gz
  sha256: ff0fa0bfc4edef8bdbbb3cabe6fdbd5481a71abbbcc2159f402dea515353ae7c

build:
  number: 0
  # not supported by upstream yet
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ native }}binutils      # [win]

test:
  commands:
    - exa --help
    - exa --icons --long --git --header

about:
  home: https://the.exa.website/
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: A modern version of ‘ls’
  dev_url: https://github.com/ogham/exa

extra:
  recipe-maintainers:
    - dbast
