travis:
  secure:
    BINSTAR_TOKEN: Jdcenk4KdAGRYxIMc6PL9PJf+mP/v2FbPZ0J5BmLVJ6+Cq1Bo30MNG1X2gtIfWbL4I5Kcpvh6l6HH0UR1s7jG20Bn/7bl6DafPHiqkbL+kB7RUqfJLmoNob8WP+KFobOcN8K1uE+01SHmmCPm1/VO6XzSfRdAwg0m7aJUBDdqYm6XYeb0PScovPD/86AZENIlmmrsVcX+vmPeOVMJwaFpm9eZ3KODo5mo8IooApkUO2qS8lw7tE7pAhHL1xMM+sC5k5cPQc7MQeoideQhkvl5RQx8vbTeURBULBKgCxv83re4Xqqh50VS5n1zT0Di2hQ3/P9eOMtChO+1Rtoyz3TeKCJNQAhn2Ub/X6kgRUCX4xD6iXGevXL+R5v6q6zwfrHKKXTPohgWrRBu/+Sg7sBnqAe2Yo9OSKrocB0bYu8A8Pp8HR8XWB1vXPGXlkoaqjWyKrdFi7QDZDrawvpt9+jJHvmTfSR/KugIVRlkcJK2/ns5xWh12k8+LTEu+nWMkf1KUmkHDMFTSSpgjiGK3GXAmzS+2mi50Z43XdF+i/M3OiEpv3tQxeQaCJVwQPQrtiaRghjBFwoE2rCc8wWnuiQlHq111tbkeYMl+1ITgnFFYzSwPVOGwypZeZJaNUpVsLNuJZPy44MR2mbBzZZFfjQbQrl/HBIkI6cYqns8/F6oWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
